# Generated by Django 5.1.7 on 2025-03-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_name', models.CharField(max_length=50)),
                ('display_type', models.CharField(choices=[('radio', 'Radio'), ('selection', 'Selection'), ('color', 'Color')], default='radio', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_end', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('promotion_value', models.IntegerField(blank=True, null=True)),
                ('promotion_value_type', models.CharField(blank=True, choices=[('FIX', 'Fix'), ('PERCENTAGE', 'Percentage')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_phone', models.CharField(max_length=10, unique=True)),
                ('cus_mail', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cus_address', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(max_length=10)),
                ('emp_mail', models.CharField(max_length=100)),
                ('emp_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('sup_phone', models.CharField(max_length=11)),
                ('sup_mail', models.CharField(max_length=100)),
                ('sup_add', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('default_extra_price', models.IntegerField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100)),
                ('cate_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('BUY_X_GET_Y', 'Buy-x-get-y')], default='DISCOUNT', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_end', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('promotion_value', models.IntegerField(blank=True, null=True)),
                ('promotion_value_type', models.CharField(blank=True, choices=[('FIX', 'Fix'), ('PERCENTAGE', 'Percentage')], max_length=10, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_tier', models.CharField(blank=True, choices=[('SILVER', 'Silver'), ('GOlD', 'Gold'), ('PLATIUM', 'Platium')], max_length=10, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coupon')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discount')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('reward_tier', models.CharField(blank=True, choices=[('SILVER', 'Silver'), ('GOlD', 'Gold'), ('PLATIUM', 'Platium')], max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer')], default='CASH', max_length=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('PENDING', 'Pending'), ('CANCEL', 'Cancel')], default='PENDING', max_length=10)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially-part')], max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_type', models.CharField(choices=[('Good', 'good'), ('Service', 'service')], default='Good', max_length=10)),
                ('barcode', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('prod_price', models.IntegerField()),
                ('prod_cost_price', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in', models.IntegerField()),
                ('quantity_out', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributevalue')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(through='api.ProductAttribute', to='api.attributevalue'),
        ),
        migrations.CreateModel(
            name='PromotionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_purchase_qty', models.IntegerField(default=0)),
                ('min_purchase_amount', models.IntegerField(default=0)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discount')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVE', 'Receive'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('contains', models.FloatField()),
                ('reference_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit')),
            ],
        ),
        migrations.CreateModel(
            name='GiftProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'unique_together': {('product', 'discount')},
            },
        ),
    ]
