# Generated by Django 5.1.7 on 2025-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_unit_contains'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='default_extra_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
