# Generated by Django 5.1.7 on 2025-03-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attributevalue_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('id', 'value')},
        ),
    ]
