# Generated by Django 5.1.7 on 2025-03-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
