# Generated by Django 5.1.7 on 2025-03-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attributevalue_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('variant_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='giftproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='discount',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productvariant'),
        ),
        migrations.AddField(
            model_name='giftproduct',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productvariant'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productvariant'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='giftproduct',
            unique_together={('variant', 'discount')},
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributevalue')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.RemoveField(
            model_name='giftproduct',
            name='product',
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(fields=('value', 'variant'), name='primary_key_variant_value'),
        ),
    ]
