# Generated by Django 5.1.7 on 2025-03-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_prod_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
