# Generated by Django 5.1.7 on 2025-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_productvariant_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
