# Generated by Django 5.1.7 on 2025-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_productvariant_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='display_type',
            field=models.CharField(choices=[('Radio', 'Radio'), ('SELECTION', 'Selection'), ('COLOR', 'Color')], default='Radio', max_length=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('DISCOUNT', 'Discount'), ('BUY_X_GET_Y', 'Buy-X-Get-Y')], default='DISCOUNT', max_length=15),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('Good', 'GOOD'), ('Service', 'SERVICE')], default='Good', max_length=10),
        ),
    ]
