# Generated by Django 5.1.7 on 2025-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_order_alter_attribute_display_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncondition',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
