# Generated by Django 5.1.7 on 2025-03-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_promotioncondition_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AlterField(
            model_name='promotioncondition',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='api.discount'),
        ),
    ]
