# Generated by Django 5.1.7 on 2025-03-30 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_discount_category_remove_discount_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=50)),
                ('min_points', models.IntegerField()),
                ('exchange_rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.rewardtier'),
        ),
    ]
