# Generated by Django 5.1.7 on 2025-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_loyaltyprogram_reward_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
