# Generated by Django 5.1.7 on 2025-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_orderdetail_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_cost_price',
            field=models.IntegerField(default=0),
        ),
    ]
