# Generated by Django 5.1.7 on 2025-04-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='api.purchaseorder'),
        ),
    ]
