# Generated by Django 5.1.7 on 2025-04-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_purchasedetail_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_order', to='api.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_coupon', to='api.coupon'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail', to='api.purchaseorder'),
        ),
    ]
