# Generated by Django 5.1.7 on 2025-04-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_customer_debt_amount_alter_invoice_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_paid',
            new_name='amount_change',
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_received',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('received_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.IntegerField(default=0)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unit')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productvariant')),
            ],
        ),
    ]
