# Generated by Django 5.1.7 on 2025-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_amount_paid_invoice_amount_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyreward',
            name='points_required',
            field=models.IntegerField(default=0),
        ),
    ]
