# Generated by Django 5.1.7 on 2025-04-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_returnorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnOrder',
        ),
    ]
