# Generated by Django 5.1.7 on 2025-04-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_returnorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField()),
                ('refund_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=1000)),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.returnorder')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productvariant')),
            ],
        ),
    ]
