# Generated by Django 5.1.7 on 2025-04-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_returndetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='start_end',
            new_name='end_date',
        ),
    ]
