# Generated by Django 5.1.7 on 2025-04-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_start_end_discount_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftproduct',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
        ),
    ]
