# Generated by Django 5.1.7 on 2025-04-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_giftproduct_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='start_end',
            new_name='end_date',
        ),
    ]
