# Generated by Django 5.1.7 on 2025-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attribute_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
    ]
