# Generated by Django 4.2.8 on 2025-05-31 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_attributevalue_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='api.productvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.category'),
        ),
        migrations.AlterField(
            model_name='promotioncondition',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='api.discount'),
        ),
        migrations.AlterField(
            model_name='variantattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantattribute', to='api.attributevalue'),
        ),
    ]
