# Generated by Django 4.2.8 on 2025-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_discount_discount_name_alter_discount_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
