# Generated by Django 4.2.8 on 2025-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_purchaseorder_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVE', 'Receive'), ('CANCELED', 'Canceled')], default='RECEIVE', max_length=10),
        ),
    ]
