# Generated by Django 4.2.8 on 2025-06-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_details', to='api.purchaseorder'),
        ),
    ]
