# Generated by Django 4.2.8 on 2025-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_purchasedetail_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
