# Generated by Django 4.2.8 on 2025-06-06 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_inventorybatch_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='api.productvariant'),
        ),
    ]
